- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  tasks:
          - name: copiar archivo 1
            shell: scp  vagrant@192.168.56.110:/home/vagrant/token.txt vagrant@192.168.56.111:/home/vagrant
            ignore_errors: yes
          - name: copiar archivo 2
            shell: scp vagrant@192.168.56.110:/home/vagrant/token.txt  vagrant@192.168.56.112:/home/vagrant
            ignore_errors: yes

          - name: copiar archivo 3
            shell: scp vagrant@192.168.56.110:/home/vagrant/token.txt  vagrant@192.168.56.113:/home/vagrant
            ignore_errors: yes

- hosts: worker_1 worker_2 worker_3
  become: yes
  become_method: sudo
  tasks:
          - name: join 1
            shell: var=`cat token.txt` && sudo docker swarm join --token $var 192.168.56.110:2377
            ignore_errors: yes
